fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -221,226 +221,220 @@ jobs:
         & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" ".\Bloret-Launcher-Setup.iss"
       shell: pwsh
 
-
-
-
-
-
-
     - name: 上传安装程序
       uses: actions/upload-artifact@v4
       with:
         name: Bloret-Launcher-Setup
         path: "./output/Bloret Launcher Setup.exe"
-  Build-macOS:
-    needs: Set-Version
-    runs-on: macos-latest
-    env:
-      PYTHON_VERSION: '3.9'
-      OUTPUT_DIR: 'output'
-      ARTIFACT_NAME: 'Bloret-Launcher-macOS.zip'
-    steps:
-    - name: 检出最新版本
-      uses: actions/checkout@v2
-      with:
-        ref: 'Windows'
-    - name: 验证资源文件路径
-      run: |
-        ls -alh .
-        [ -f "bloret.ico" ] || (echo "bloret.ico not found" && exit 1)
-        [ -f "config.json" ] || (echo "config.json not found" && exit 1)
-        [ -d "ui" ] || (echo "ui directory not found" && exit 1)
-        [ -d "lang" ] || (echo "lang directory not found" && exit 1)
-        [ -f "cmcl.json" ] || (echo "cmcl.json not found" && exit 1)
-        [ -f "cmcl.exe" ] || (echo "cmcl.exe not found" && exit 1)
-        [ -f "cmcl.blank.json" ] || (echo "cmcl.blank.json not found" && exit 1)
-        [ -f "frpc.exe" ] || (echo "frpc.exe not found" && exit 1)
-        [ -f "frpc.toml" ] || (echo "frpc.toml not found" && exit 1)
-        [ -f "JavaWrapper.jar" ] || (echo "JavaWrapper.jar not found" && exit 1)
-      shell: bash
-    - name: 设置 Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-    - name: 过滤依赖
-      run: |
-        grep -ivE '^(pywin32|win11toast|winsdk)' requirements.txt > requirements_nopywin32.txt
-      shell: bash
-    - name: 安装依赖
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements_nopywin32.txt
-        pip install pillow pyinstaller
-      shell: bash
-    - name: 使用 PyInstaller 打包
-      run: |
-        pyinstaller --onefile --windowed --name=Bloret-Launcher \
-          --add-data "bloret.ico:." \
-          --add-data "config.json:." \
-          --add-data "ui:ui" \
-          --add-data "lang:lang" \
-          --add-data "cmcl.json:." \
-          --add-data "cmcl.exe:." \
-          --add-data "cmcl.blank.json:." \
-          --add-data "frpc.exe:." \
-          --add-data "frpc.toml:." \
-          --add-data "JavaWrapper.jar:." \
-          --hidden-import=sip \
-          --hidden-import=qfluentwidgets \
-          --hidden-import=win11toast \
-          --hidden-import=toml \
-          --paths=. \
-          Bloret-Launcher.py
-      shell: bash
+  # Build-macOS:
+  #   needs: Set-Version
+  #   runs-on: macos-latest
+  #   env:
+  #     PYTHON_VERSION: '3.9'
+  #     OUTPUT_DIR: 'output'
+  #     ARTIFACT_NAME: 'Bloret-Launcher-macOS.zip'
+  #   steps:
+  #   - name: 检出最新版本
+  #     uses: actions/checkout@v2
+  #     with:
+  #       ref: 'Windows'
+  #   - name: 验证资源文件路径
+  #     run: |
+  #       ls -alh .
+  #       [ -f "bloret.ico" ] || (echo "bloret.ico not found" && exit 1)
+  #       [ -f "config.json" ] || (echo "config.json not found" && exit 1)
+  #       [ -d "ui" ] || (echo "ui directory not found" && exit 1)
+  #       [ -d "lang" ] || (echo "lang directory not found" && exit 1)
+  #       [ -f "cmcl.json" ] || (echo "cmcl.json not found" && exit 1)
+  #       [ -f "cmcl.exe" ] || (echo "cmcl.exe not found" && exit 1)
+  #       [ -f "cmcl.blank.json" ] || (echo "cmcl.blank.json not found" && exit 1)
+  #       [ -f "frpc.exe" ] || (echo "frpc.exe not found" && exit 1)
+  #       [ -f "frpc.toml" ] || (echo "frpc.toml not found" && exit 1)
+  #       [ -f "JavaWrapper.jar" ] || (echo "JavaWrapper.jar not found" && exit 1)
+  #     shell: bash
+  #   - name: 设置 Python
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: ${{ env.PYTHON_VERSION }}
+  #   - name: 过滤依赖
+  #     run: |
+  #       grep -ivE '^(pywin32|win11toast|winsdk)' requirements.txt > requirements_nopywin32.txt
+  #     shell: bash
+  #   - name: 安装依赖
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       pip install -r requirements_nopywin32.txt
+  #       pip install pillow pyinstaller
+  #     shell: bash
+  #   - name: 使用 PyInstaller 打包
+  #     run: |
+  #       pyinstaller --onefile --windowed --name=Bloret-Launcher \
+  #         --add-data "bloret.ico:." \
+  #         --add-data "config.json:." \
+  #         --add-data "ui:ui" \
+  #         --add-data "lang:lang" \
+  #         --add-data "cmcl.json:." \
+  #         --add-data "cmcl.exe:." \
+  #         --add-data "cmcl.blank.json:." \
+  #         --add-data "frpc.exe:." \
+  #         --add-data "frpc.toml:." \
+  #         --add-data "JavaWrapper.jar:." \
+  #         --hidden-import=sip \
+  #         --hidden-import=qfluentwidgets \
+  #         --hidden-import=win11toast \
+  #         --hidden-import=toml \
+  #         --paths=. \
+  #         Bloret-Launcher.py
+  #     shell: bash
 
-    - name: 创建包含其他文件夹的目录
-      run: |
-        mkdir -p ${{ env.OUTPUT_DIR }}
-        cp dist/Bloret-Launcher ${{ env.OUTPUT_DIR }}/
-        cp -r ui/ ${{ env.OUTPUT_DIR }}/
-        cp -r lang/ ${{ env.OUTPUT_DIR }}/
-        cp cmcl.exe ${{ env.OUTPUT_DIR }}/
-        cp cmcl.json ${{ env.OUTPUT_DIR }}/
-        cp cmcl.blank.json ${{ env.OUTPUT_DIR }}/
-        cp config.json ${{ env.OUTPUT_DIR }}/
-        cp LICENSE ${{ env.OUTPUT_DIR }}/
-        cp servers.dat ${{ env.OUTPUT_DIR }}/ || true
-        cp cmcl_save.json ${{ env.OUTPUT_DIR }}/ || true
-        cp bloret.ico ${{ env.OUTPUT_DIR }}/
-        cp frpc.exe ${{ env.OUTPUT_DIR }}/
-        cp frpc.toml ${{ env.OUTPUT_DIR }}/
-        cp JavaWrapper.jar ${{ env.OUTPUT_DIR }}/
-      shell: bash
-    - name: 清理旧压缩包
-      run: |
-        [ -f "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" ] && rm "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" || true
-      shell: bash
-    - name: 创建压缩包
-      run: zip -r "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" ${{ env.OUTPUT_DIR }}/*
-      shell: bash
-    - name: 上传构建产物
-      uses: actions/upload-artifact@v4
-      with:
-        name: Bloret-Launcher-macOS
-        path: "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}"
-  Build-Linux:
-    needs: Set-Version
-    runs-on: ubuntu-latest
-    env:
-      PYTHON_VERSION: '3.9'
-      OUTPUT_DIR: 'output'
-      ARTIFACT_NAME: 'Bloret-Launcher-Linux.zip'
-    steps:
-    - name: 检出最新版本
-      uses: actions/checkout@v2
-      with:
-        ref: 'Windows'
-    - name: 验证资源文件路径
-      run: |
-        ls -alh .
-        [ -f "bloret.ico" ] || (echo "bloret.ico not found" && exit 1)
-        [ -f "config.json" ] || (echo "config.json not found" && exit 1)
-        [ -d "ui" ] || (echo "ui directory not found" && exit 1)
-        [ -d "lang" ] || (echo "lang directory not found" && exit 1)
-        [ -f "cmcl.json" ] || (echo "cmcl.json not found" && exit 1)
-        [ -f "cmcl.exe" ] || (echo "cmcl.exe not found" && exit 1)
-        [ -f "cmcl.blank.json" ] || (echo "cmcl.blank.json not found" && exit 1)
-        [ -f "frpc.exe" ] || (echo "frpc.exe not found" && exit 1)
-        [ -f "frpc.toml" ] || (echo "frpc.toml not found" && exit 1)
-        [ -f "JavaWrapper.jar" ] || (echo "JavaWrapper.jar not found" && exit 1)
-      shell: bash
-    - name: 设置 Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-    - name: 过滤依赖
-      run: |
-        grep -ivE '^(pywin32|win11toast|winsdk)' requirements.txt > requirements_nopywin32.txt
-      shell: bash
-    - name: 安装依赖
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements_nopywin32.txt
-        pip install pillow pyinstaller
-      shell: bash
-    - name: 使用 PyInstaller 打包
-      run: |
-        pyinstaller --onefile --windowed --name=Bloret-Launcher \
-          --add-data "bloret.ico:." \
-          --add-data "config.json:." \
-          --add-data "ui:ui" \
-          --add-data "lang:lang" \
-          --add-data "cmcl.json:." \
-          --add-data "cmcl.exe:." \
-          --add-data "cmcl.blank.json:." \
-          --add-data "frpc.exe:." \
-          --add-data "frpc.toml:." \
-          --add-data "JavaWrapper.jar:." \
-          --hidden-import=sip \
-          --hidden-import=qfluentwidgets \
-          --hidden-import=win11toast \
-          --hidden-import=toml \
-          --paths=. \
-          Bloret-Launcher.py
-      shell: bash
-    - name: 创建包含其他文件夹的目录
-      run: |
-        mkdir -p ${{ env.OUTPUT_DIR }}
-        cp dist/Bloret-Launcher ${{ env.OUTPUT_DIR }}/
-        cp -r ui/ ${{ env.OUTPUT_DIR }}/
-        cp -r lang/ ${{ env.OUTPUT_DIR }}/
-        cp cmcl.exe ${{ env.OUTPUT_DIR }}/
-        cp cmcl.json ${{ env.OUTPUT_DIR }}/
-        cp cmcl.blank.json ${{ env.OUTPUT_DIR }}/
-        cp config.json ${{ env.OUTPUT_DIR }}/
-        cp LICENSE ${{ env.OUTPUT_DIR }}/
-        cp servers.dat ${{ env.OUTPUT_DIR }}/ || true
-        cp cmcl_save.json ${{ env.OUTPUT_DIR }}/ || true
-        cp bloret.ico ${{ env.OUTPUT_DIR }}/
-        cp frpc.exe ${{ env.OUTPUT_DIR }}/
-        cp frpc.toml ${{ env.OUTPUT_DIR }}/
-        cp JavaWrapper.jar ${{ env.OUTPUT_DIR }}/
-      shell: bash
-    - name: 清理旧压缩包
-      run: |
-        [ -f "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" ] && rm "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" || true
-      shell: bash
-    - name: 创建压缩包
-      run: zip -r "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" ${{ env.OUTPUT_DIR }}/*
-      shell: bash
-    - name: 上传构建产物
-      uses: actions/upload-artifact@v4
-      with:
-        name: Bloret-Launcher-Linux
-        path: "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}"
+  #   - name: 创建包含其他文件夹的目录
+  #     run: |
+  #       mkdir -p ${{ env.OUTPUT_DIR }}
+  #       cp dist/Bloret-Launcher ${{ env.OUTPUT_DIR }}/
+  #       cp -r ui/ ${{ env.OUTPUT_DIR }}/
+  #       cp -r lang/ ${{ env.OUTPUT_DIR }}/
+  #       cp cmcl.exe ${{ env.OUTPUT_DIR }}/
+  #       cp cmcl.json ${{ env.OUTPUT_DIR }}/
+  #       cp cmcl.blank.json ${{ env.OUTPUT_DIR }}/
+  #       cp config.json ${{ env.OUTPUT_DIR }}/
+  #       cp LICENSE ${{ env.OUTPUT_DIR }}/
+  #       cp servers.dat ${{ env.OUTPUT_DIR }}/ || true
+  #       cp cmcl_save.json ${{ env.OUTPUT_DIR }}/ || true
+  #       cp bloret.ico ${{ env.OUTPUT_DIR }}/
+  #       cp frpc.exe ${{ env.OUTPUT_DIR }}/
+  #       cp frpc.toml ${{ env.OUTPUT_DIR }}/
+  #       cp JavaWrapper.jar ${{ env.OUTPUT_DIR }}/
+  #     shell: bash
+  #   - name: 清理旧压缩包
+  #     run: |
+  #       [ -f "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" ] && rm "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" || true
+  #     shell: bash
+  #   - name: 创建压缩包
+  #     run: zip -r "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" ${{ env.OUTPUT_DIR }}/*
+  #     shell: bash
+  #   - name: 上传构建产物
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: Bloret-Launcher-macOS
+  #       path: "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}"
+  # Build-Linux:
+  #   needs: Set-Version
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     PYTHON_VERSION: '3.9'
+  #     OUTPUT_DIR: 'output'
+  #     ARTIFACT_NAME: 'Bloret-Launcher-Linux.zip'
+  #   steps:
+  #   - name: 检出最新版本
+  #     uses: actions/checkout@v2
+  #     with:
+  #       ref: 'Windows'
+  #   - name: 验证资源文件路径
+  #     run: |
+  #       ls -alh .
+  #       [ -f "bloret.ico" ] || (echo "bloret.ico not found" && exit 1)
+  #       [ -f "config.json" ] || (echo "config.json not found" && exit 1)
+  #       [ -d "ui" ] || (echo "ui directory not found" && exit 1)
+  #       [ -d "lang" ] || (echo "lang directory not found" && exit 1)
+  #       [ -f "cmcl.json" ] || (echo "cmcl.json not found" && exit 1)
+  #       [ -f "cmcl.exe" ] || (echo "cmcl.exe not found" && exit 1)
+  #       [ -f "cmcl.blank.json" ] || (echo "cmcl.blank.json not found" && exit 1)
+  #       [ -f "frpc.exe" ] || (echo "frpc.exe not found" && exit 1)
+  #       [ -f "frpc.toml" ] || (echo "frpc.toml not found" && exit 1)
+  #       [ -f "JavaWrapper.jar" ] || (echo "JavaWrapper.jar not found" && exit 1)
+  #     shell: bash
+  #   - name: 设置 Python
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: ${{ env.PYTHON_VERSION }}
+  #   - name: 过滤依赖
+  #     run: |
+  #       grep -ivE '^(pywin32|win11toast|winsdk)' requirements.txt > requirements_nopywin32.txt
+  #     shell: bash
+  #   - name: 安装依赖
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       pip install -r requirements_nopywin32.txt
+  #       pip install pillow pyinstaller
+  #     shell: bash
+  #   - name: 使用 PyInstaller 打包
+  #     run: |
+  #       pyinstaller --onefile --windowed --name=Bloret-Launcher \
+  #         --add-data "bloret.ico:." \
+  #         --add-data "config.json:." \
+  #         --add-data "ui:ui" \
+  #         --add-data "lang:lang" \
+  #         --add-data "cmcl.json:." \
+  #         --add-data "cmcl.exe:." \
+  #         --add-data "cmcl.blank.json:." \
+  #         --add-data "frpc.exe:." \
+  #         --add-data "frpc.toml:." \
+  #         --add-data "JavaWrapper.jar:." \
+  #         --hidden-import=sip \
+  #         --hidden-import=qfluentwidgets \
+  #         --hidden-import=win11toast \
+  #         --hidden-import=toml \
+  #         --paths=. \
+  #         Bloret-Launcher.py
+  #     shell: bash
+  #   - name: 创建包含其他文件夹的目录
+  #     run: |
+  #       mkdir -p ${{ env.OUTPUT_DIR }}
+  #       cp dist/Bloret-Launcher ${{ env.OUTPUT_DIR }}/
+  #       cp -r ui/ ${{ env.OUTPUT_DIR }}/
+  #       cp -r lang/ ${{ env.OUTPUT_DIR }}/
+  #       cp cmcl.exe ${{ env.OUTPUT_DIR }}/
+  #       cp cmcl.json ${{ env.OUTPUT_DIR }}/
+  #       cp cmcl.blank.json ${{ env.OUTPUT_DIR }}/
+  #       cp config.json ${{ env.OUTPUT_DIR }}/
+  #       cp LICENSE ${{ env.OUTPUT_DIR }}/
+  #       cp servers.dat ${{ env.OUTPUT_DIR }}/ || true
+  #       cp cmcl_save.json ${{ env.OUTPUT_DIR }}/ || true
+  #       cp bloret.ico ${{ env.OUTPUT_DIR }}/
+  #       cp frpc.exe ${{ env.OUTPUT_DIR }}/
+  #       cp frpc.toml ${{ env.OUTPUT_DIR }}/
+  #       cp JavaWrapper.jar ${{ env.OUTPUT_DIR }}/
+  #     shell: bash
+  #   - name: 清理旧压缩包
+  #     run: |
+  #       [ -f "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" ] && rm "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" || true
+  #     shell: bash
+  #   - name: 创建压缩包
+  #     run: zip -r "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}" ${{ env.OUTPUT_DIR }}/*
+  #     shell: bash
+  #   - name: 上传构建产物
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: Bloret-Launcher-Linux
+  #       path: "${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }}"
 
-  Collect-Artifacts:
-    needs: [Build-Windows, Build-macOS, Build-Linux]
-    runs-on: ubuntu-latest
-    steps:
-      - name: 下载 Windows 构建产物
-        uses: actions/download-artifact@v4
-        with:
-          name: Bloret-Launcher
-          path: output/all/windows
-      - name: 下载 macOS 构建产物
-        uses: actions/download-artifact@v4
-        with:
-          name: Bloret-Launcher-macOS
-          path: output/all/macos
-      - name: 下载 Linux 构建产物
-        uses: actions/download-artifact@v4
-        with:
-          name: Bloret-Launcher-Linux
-          path: output/all/linux
-      - name: 展示收集到的产物
-        run: |
-          ls -alR output/all
-      - name: 上传所有平台产物
-        uses: actions/upload-artifact@v4
-        with:
-          name: Bloret-Launcher-All
-          path: output/all/
+  # Collect-Artifacts:
+  #   needs: [Build-Windows, Build-macOS, Build-Linux]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 下载 Windows 构建产物
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: Bloret-Launcher
+  #         path: output/all/windows
+  #     - name: 下载 macOS 构建产物
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: Bloret-Launcher-macOS
+  #         path: output/all/macos
+  #     - name: 下载 Linux 构建产物
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: Bloret-Launcher-Linux
+  #         path: output/all/linux
+  #     - name: 展示收集到的产物
+  #       run: |
+  #         ls -alR output/all
+  #     - name: 上传所有平台产物
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Bloret-Launcher-All
+  #         path: output/all/
 
   # release:
   #   needs: [Build, Code-Package, Build-Setup]
